"""Catálogo inicial de roles y permisos (Fase 1)."""

from __future__ import annotations

PERMISSIONS: list[dict[str, str]] = [
    {"code": "dashboard.view", "name": "Ver dashboard", "module": "dashboard"},
    {"code": "branches.view", "name": "Ver sucursales", "module": "branches"},
    {"code": "branches.manage", "name": "Administrar sucursales", "module": "branches"},
    {"code": "users.view", "name": "Ver usuarios", "module": "users"},
    {"code": "users.manage", "name": "Administrar usuarios", "module": "users"},
    {"code": "settings.view", "name": "Ver configuración", "module": "settings"},
    {"code": "settings.manage", "name": "Administrar configuración", "module": "settings"},
    {"code": "audit.view", "name": "Ver auditoría", "module": "audit"},
    {"code": "reports.view", "name": "Ver reportes de sucursal", "module": "reports"},
    {"code": "reports.global", "name": "Ver reportes globales", "module": "reports"},
    {"code": "customers.view", "name": "Ver clientes", "module": "customers"},
    {"code": "customers.manage", "name": "Administrar clientes", "module": "customers"},
    {"code": "deliverers.view", "name": "Ver personas que entregan", "module": "deliverers"},
    {"code": "deliverers.manage", "name": "Administrar personas que entregan", "module": "deliverers"},
    {"code": "items.view", "name": "Ver artículos", "module": "items"},
    {"code": "items.manage", "name": "Administrar artículos", "module": "items"},
    {"code": "pawn.view", "name": "Ver empeños", "module": "pawn"},
    {"code": "pawn.manage", "name": "Administrar empeños", "module": "pawn"},
    {"code": "payments.view", "name": "Ver pagos", "module": "payments"},
    {"code": "payments.manage", "name": "Registrar pagos", "module": "payments"},
    {"code": "purchases.view", "name": "Ver compras", "module": "purchases"},
    {"code": "purchases.manage", "name": "Registrar compras", "module": "purchases"},
    {"code": "sales.view", "name": "Ver ventas", "module": "sales"},
    {"code": "sales.manage", "name": "Registrar ventas", "module": "sales"},
    {"code": "inventory.view", "name": "Ver inventario", "module": "inventory"},
    {"code": "inventory.manage", "name": "Administrar inventario", "module": "inventory"},
    {"code": "cash.view", "name": "Ver caja", "module": "cash"},
    {"code": "cash.manage", "name": "Operar caja", "module": "cash"},
    {"code": "expenses.view", "name": "Ver gastos", "module": "expenses"},
    {"code": "expenses.manage", "name": "Administrar gastos", "module": "expenses"},
    {"code": "exceptions.authorize", "name": "Autorizar excepciones", "module": "security"},
    {"code": "operations.void", "name": "Anular operaciones", "module": "security"},
    {"code": "percentages.manage", "name": "Configurar porcentajes", "module": "settings"},
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "superadmin": ["*"],
    "admin": [
        "dashboard.view",
        "branches.view",
        "users.view",
        "users.manage",
        "settings.view",
        "audit.view",
        "reports.view",
        "customers.view",
        "customers.manage",
        "deliverers.view",
        "deliverers.manage",
        "items.view",
        "items.manage",
        "pawn.view",
        "pawn.manage",
        "payments.view",
        "payments.manage",
        "purchases.view",
        "purchases.manage",
        "sales.view",
        "sales.manage",
        "inventory.view",
        "inventory.manage",
        "cash.view",
        "cash.manage",
        "expenses.view",
        "expenses.manage",
        "exceptions.authorize",
    ],
    "cashier": [
        "dashboard.view",
        "customers.view",
        "customers.manage",
        "deliverers.view",
        "deliverers.manage",
        "items.view",
        "items.manage",
        "pawn.view",
        "pawn.manage",
        "payments.view",
        "payments.manage",
        "purchases.view",
        "purchases.manage",
        "sales.view",
        "sales.manage",
        "inventory.view",
        "cash.view",
        "cash.manage",
    ],
    "auditor": [
        "dashboard.view",
        "branches.view",
        "users.view",
        "settings.view",
        "audit.view",
        "reports.view",
        "reports.global",
        "customers.view",
        "deliverers.view",
        "items.view",
        "pawn.view",
        "payments.view",
        "purchases.view",
        "sales.view",
        "inventory.view",
        "cash.view",
        "expenses.view",
    ],
}

ROLES: list[dict[str, str]] = [
    {
        "code": "superadmin",
        "name": "Superadministrador",
        "description": "Acceso total a todas las sucursales y configuración.",
    },
    {
        "code": "admin",
        "name": "Administrador",
        "description": "Administra su sucursal y autoriza excepciones.",
    },
    {
        "code": "cashier",
        "name": "Cajero / Empleado",
        "description": "Operaciones diarias en su sucursal.",
    },
    {
        "code": "auditor",
        "name": "Auditor",
        "description": "Solo consulta y reportes; sin modificaciones.",
    },
]

DEFAULT_SETTINGS: list[dict[str, str]] = [
    {
        "key": "business_name",
        "value": "JDM Empeños",
        "category": "general",
        "label": "Nombre del negocio",
    },
    {
        "key": "business_rnc",
        "value": "",
        "category": "general",
        "label": "RNC",
    },
    {
        "key": "business_phone",
        "value": "",
        "category": "general",
        "label": "Teléfono",
    },
    {
        "key": "business_whatsapp",
        "value": "",
        "category": "general",
        "label": "WhatsApp",
    },
    {
        "key": "business_email",
        "value": "",
        "category": "general",
        "label": "Correo",
    },
    {
        "key": "business_address",
        "value": "",
        "category": "general",
        "label": "Dirección",
    },
    {
        "key": "currency_symbol",
        "value": "RD$",
        "category": "general",
        "label": "Símbolo de moneda",
    },
    {
        "key": "timezone",
        "value": "America/Santo_Domingo",
        "category": "general",
        "label": "Zona horaria",
    },
    {
        "key": "default_interest_percent",
        "value": "10",
        "category": "finance",
        "label": "Porcentaje de interés predeterminado",
        "value_type": "decimal",
    },
    {
        "key": "default_grace_days",
        "value": "3",
        "category": "finance",
        "label": "Días de gracia predeterminados",
        "value_type": "integer",
    },
    {
        "key": "default_duration_days",
        "value": "30",
        "category": "finance",
        "label": "Duración predeterminada (días)",
        "value_type": "integer",
    },
]