"""fase3_a_6_operaciones

Revision ID: 06eeae71d3c0
Revises: 83ca8cbefb9c
Create Date: 2026-07-22 19:20:04.178184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eeae71d3c0'
down_revision = '83ca8cbefb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fee_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fee_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('scope_ref', sa.String(length=80), nullable=True),
    sa.Column('percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('interest_type', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('days_before_apply', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'branch_id', name='uq_cash_register_branch')
    )
    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_registers_branch_id'), ['branch_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_path', sa.String(length=500), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['cash_registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_register_id'), ['register_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_status'), ['status'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('concept', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('related_type', sa.String(length=60), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_session_id'), ['session_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('cash_received', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_sales_invoice')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('sale_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_payments_sale_id'), ['sale_id'], unique=False)

    op.create_table('direct_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_number', sa.String(length=40), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('negotiated_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deliverer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['deliverer_id'], ['deliverers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_number', name='uq_direct_purchase_number')
    )
    with op.batch_alter_table('direct_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_purchases_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_purchases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_purchases_deliverer_id'), ['deliverer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_purchases_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_purchases_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_purchases_purchase_number'), ['purchase_number'], unique=False)

    op.create_table('item_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_movements_item_id'), ['item_id'], unique=False)

    op.create_table('pawn_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('capital_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('late_fee_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('interest_type', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=40), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fees_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('percent_manual', sa.Boolean(), nullable=False),
    sa.Column('percent_original', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('percent_change_reason', sa.Text(), nullable=True),
    sa.Column('percent_authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('payment_order', sa.String(length=80), nullable=False),
    sa.Column('late_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('late_fixed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('late_mode', sa.String(length=40), nullable=False),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_for_inventory', sa.Boolean(), nullable=False),
    sa.Column('authorized_inventory_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_inventory_by_id', sa.Integer(), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('parent_contract_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deliverer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['deliverer_id'], ['deliverers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['pawn_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number', name='uq_pawn_contract_number')
    )
    with op.batch_alter_table('pawn_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pawn_contracts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_contract_number'), ['contract_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_deliverer_id'), ['deliverer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_contracts_status'), ['status'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_item_id'), ['item_id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_branch_id', sa.Integer(), nullable=False),
    sa.Column('to_branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['to_branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_item_id'), ['item_id'], unique=False)

    op.create_table('warranties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    with op.batch_alter_table('warranties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warranties_sale_id'), ['sale_id'], unique=False)

    op.create_table('pawn_contract_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['pawn_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pawn_contract_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pawn_contract_versions_contract_id'), ['contract_id'], unique=False)

    op.create_table('pawn_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('payment_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payer_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['pawn_contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number', name='uq_pawn_payment_receipt')
    )
    with op.batch_alter_table('pawn_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pawn_payments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_payments_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_payments_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_pawn_payments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_pawn_payments_receipt_number'), ['receipt_number'], unique=False)

    op.create_table('pawn_payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['pawn_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pawn_payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pawn_payment_allocations_payment_id'), ['payment_id'], unique=False)

    op.create_table('renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renewal_number', sa.String(length=50), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_due_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('percent_applied', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('renewed_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['pawn_contracts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['pawn_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('renewal_number')
    )
    with op.batch_alter_table('renewals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewals_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renewals_contract_id'))

    op.drop_table('renewals')
    with op.batch_alter_table('pawn_payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pawn_payment_allocations_payment_id'))

    op.drop_table('pawn_payment_allocations')
    with op.batch_alter_table('pawn_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pawn_payments_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_pawn_payments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_pawn_payments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_pawn_payments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_pawn_payments_contract_id'))
        batch_op.drop_index(batch_op.f('ix_pawn_payments_branch_id'))

    op.drop_table('pawn_payments')
    with op.batch_alter_table('pawn_contract_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pawn_contract_versions_contract_id'))

    op.drop_table('pawn_contract_versions')
    with op.batch_alter_table('warranties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warranties_sale_id'))

    op.drop_table('warranties')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_item_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_item_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_sale_id'))

    op.drop_table('returns')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_item_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_is_deleted'))

    op.drop_table('reservations')
    with op.batch_alter_table('pawn_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_item_id'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_due_date'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_deliverer_id'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_contract_number'))
        batch_op.drop_index(batch_op.f('ix_pawn_contracts_branch_id'))

    op.drop_table('pawn_contracts')
    with op.batch_alter_table('item_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_movements_item_id'))

    op.drop_table('item_movements')
    with op.batch_alter_table('direct_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_purchases_purchase_number'))
        batch_op.drop_index(batch_op.f('ix_direct_purchases_item_id'))
        batch_op.drop_index(batch_op.f('ix_direct_purchases_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_direct_purchases_deliverer_id'))
        batch_op.drop_index(batch_op.f('ix_direct_purchases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_direct_purchases_branch_id'))

    op.drop_table('direct_purchases')
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payments_sale_id'))

    op.drop_table('sale_payments')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))

    op.drop_table('sales')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_session_id'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_is_deleted'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_cash_sessions_register_id'))
        batch_op.drop_index(batch_op.f('ix_cash_sessions_branch_id'))

    op.drop_table('cash_sessions')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_expenses_branch_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_registers_branch_id'))

    op.drop_table('cash_registers')
    op.drop_table('penalties')
    op.drop_table('interest_rules')
    op.drop_table('fee_rules')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
