"""fase2_clientes_entregas_articulos

Revision ID: 83ca8cbefb9c
Revises: 107a25d52184
Create Date: 2026-07-22 19:08:06.962154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ca8cbefb9c'
down_revision = '107a25d52184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('related_type', sa.String(length=60), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_deliverer_id'), ['deliverer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_evidence_type'), ['evidence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_purchase_id'), ['purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_related_type'), ['related_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_sha256_hash'), ['sha256_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_uuid'), ['uuid'], unique=True)

    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('requires_imei', sa.Boolean(), nullable=False),
    sa.Column('requires_serial', sa.Boolean(), nullable=False),
    sa.Column('is_vehicle', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_item_categories_code')
    )
    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_categories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_categories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('operation_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=60), nullable=False),
    sa.Column('related_type', sa.String(length=60), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('missing_item', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorized_by_id', sa.Integer(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_exceptions_exception_type'), ['exception_type'], unique=False)

    op.create_table('operation_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signer_role', sa.String(length=40), nullable=False),
    sa.Column('related_type', sa.String(length=60), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('declaration_text', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_signatures_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_signatures_related_type'), ['related_type'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=40), nullable=False),
    sa.Column('passport', sa.String(length=40), nullable=True),
    sa.Column('other_document', sa.String(length=60), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=False),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('workplace', sa.String(length=150), nullable=True),
    sa.Column('approximate_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reference_name', sa.String(length=150), nullable=True),
    sa.Column('reference_phone', sa.String(length=30), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('document_front_path', sa.String(length=500), nullable=True),
    sa.Column('document_back_path', sa.String(length=500), nullable=True),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duplicate_authorized', sa.Boolean(), nullable=False),
    sa.Column('duplicate_authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_authorization_reason', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_passport'), ['passport'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_primary'), ['phone_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_documents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_documents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_documents_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('customer_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('relationship_type', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_references_customer_id'), ['customer_id'], unique=False)

    op.create_table('deliverers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('is_same_as_customer', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=40), nullable=False),
    sa.Column('passport', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('relationship_to_customer', sa.String(length=120), nullable=True),
    sa.Column('delivery_reason', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('document_front_path', sa.String(length=500), nullable=True),
    sa.Column('document_back_path', sa.String(length=500), nullable=True),
    sa.Column('holding_item_photo_path', sa.String(length=500), nullable=True),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('legitimate_origin_accepted', sa.Boolean(), nullable=False),
    sa.Column('declaration_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declaration_ip', sa.String(length=64), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliverers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverers_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliverers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverers_phone'), ['phone'], unique=False)

    op.create_table('deliverer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['deliverers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliverer_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverer_documents_deliverer_id'), ['deliverer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverer_documents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverer_documents_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('deliverer_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverer_id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('accepted_declaration', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deliverer_id'], ['deliverers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliverer_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverer_signatures_deliverer_id'), ['deliverer_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('barcode', sa.String(length=80), nullable=True),
    sa.Column('qr_code', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('imei', sa.String(length=40), nullable=True),
    sa.Column('chassis_number', sa.String(length=80), nullable=True),
    sa.Column('plate_number', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('physical_condition', sa.String(length=80), nullable=True),
    sa.Column('functional_condition', sa.String(length=80), nullable=True),
    sa.Column('damages', sa.Text(), nullable=True),
    sa.Column('scratches', sa.Text(), nullable=True),
    sa.Column('missing_parts', sa.Text(), nullable=True),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('shelf', sa.String(length=60), nullable=True),
    sa.Column('warehouse', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('duplicate_authorized', sa.Boolean(), nullable=False),
    sa.Column('duplicate_authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_authorization_reason', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['deliverer_id'], ['deliverers.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_chassis_number'), ['chassis_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_deliverer_id'), ['deliverer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_imei'), ['imei'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_qr_code'), ['qr_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)

    op.create_table('item_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('new_value_approx', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('used_value_approx', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('physical_condition', sa.String(length=80), nullable=True),
    sa.Column('functional_condition', sa.String(length=80), nullable=True),
    sa.Column('recommended_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('suggested_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=40), nullable=True),
    sa.Column('sale_ease', sa.String(length=40), nullable=True),
    sa.Column('demand_level', sa.String(length=40), nullable=True),
    sa.Column('evaluator_notes', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('evaluated_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_evaluations_item_id'), ['item_id'], unique=False)

    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=60), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_images_image_type'), ['image_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_images_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_images_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_images_sha256_hash'), ['sha256_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_images_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_item_images_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_images_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_item_images_image_type'))

    op.drop_table('item_images')
    with op.batch_alter_table('item_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_evaluations_item_id'))

    op.drop_table('item_evaluations')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_serial_number'))
        batch_op.drop_index(batch_op.f('ix_items_qr_code'))
        batch_op.drop_index(batch_op.f('ix_items_plate_number'))
        batch_op.drop_index(batch_op.f('ix_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_items_imei'))
        batch_op.drop_index(batch_op.f('ix_items_deliverer_id'))
        batch_op.drop_index(batch_op.f('ix_items_customer_id'))
        batch_op.drop_index(batch_op.f('ix_items_code'))
        batch_op.drop_index(batch_op.f('ix_items_chassis_number'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_items_brand'))
        batch_op.drop_index(batch_op.f('ix_items_branch_id'))
        batch_op.drop_index(batch_op.f('ix_items_barcode'))

    op.drop_table('items')
    with op.batch_alter_table('deliverer_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverer_signatures_deliverer_id'))

    op.drop_table('deliverer_signatures')
    with op.batch_alter_table('deliverer_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverer_documents_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_deliverer_documents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_deliverer_documents_deliverer_id'))

    op.drop_table('deliverer_documents')
    with op.batch_alter_table('deliverers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverers_phone'))
        batch_op.drop_index(batch_op.f('ix_deliverers_national_id'))
        batch_op.drop_index(batch_op.f('ix_deliverers_last_name'))
        batch_op.drop_index(batch_op.f('ix_deliverers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_deliverers_first_name'))
        batch_op.drop_index(batch_op.f('ix_deliverers_customer_id'))
        batch_op.drop_index(batch_op.f('ix_deliverers_code'))
        batch_op.drop_index(batch_op.f('ix_deliverers_branch_id'))

    op.drop_table('deliverers')
    with op.batch_alter_table('customer_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_references_customer_id'))

    op.drop_table('customer_references')
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_documents_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_customer_documents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_customer_documents_customer_id'))

    op.drop_table('customer_documents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_phone_primary'))
        batch_op.drop_index(batch_op.f('ix_customers_passport'))
        batch_op.drop_index(batch_op.f('ix_customers_national_id'))
        batch_op.drop_index(batch_op.f('ix_customers_last_name'))
        batch_op.drop_index(batch_op.f('ix_customers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_customers_first_name'))
        batch_op.drop_index(batch_op.f('ix_customers_code'))
        batch_op.drop_index(batch_op.f('ix_customers_branch_id'))

    op.drop_table('customers')
    with op.batch_alter_table('operation_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_signatures_related_type'))
        batch_op.drop_index(batch_op.f('ix_operation_signatures_related_id'))

    op.drop_table('operation_signatures')
    with op.batch_alter_table('operation_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_exceptions_exception_type'))

    op.drop_table('operation_exceptions')
    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_item_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_item_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_item_categories_code'))

    op.drop_table('item_categories')
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_uuid'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_related_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_related_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_item_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_evidence_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_deliverer_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_customer_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_contract_id'))

    op.drop_table('evidence_files')
    # ### end Alembic commands ###
